version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/testdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
  db:
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=testdb
    ports:
      - "3306:3306"